[package]
name = "platform-prototype"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
image = "0.25.1"
pollster = "0.3.0"
wgpu = "0.20.1"
winit = { version = "0.30.3", features = ["rwh_06"] }
