[package]
name = "platform-prototype"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "1.16.3", features = ["derive"] }
image = "0.25.2"
pollster = "0.3.0"
wgpu = "22.0.0"
winit = { version = "0.30.4", features = ["rwh_06"] }
